/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lowleveldesign.app;

import lowleveldesign.observable.Notify;
import lowleveldesign.observable.Observable;
import lowleveldesign.observer.Observer;
import lowleveldesign.observer.Client;

public class App {
    public static void main(String[] args) {
//this is for observer design pattern
        Observable observable = new Notify();
        Observer observer = new Client(observable, "abc@gmail.com");
        observable.add(observer);
        observable.addInventory();

    }
}
